export const LoginPage = {
  loginComponentID: '[id="authLogin"]',
  signUpButtonMainText: 'Sign Up',
  signUpComponentID: '[id="authRegister"]',
  firstNameInputFieldID: '[id="FirstName"]',
  lastNameInputFieldID: '[id="LastName"]',
  userNameInputFieldID: '[id="Username"],[id="username"]',
  emailInputFieldID: '[id="Email"]',
  passwordInputFieldID: '[id="Password"],[name="password"]',
  confirmPasswordInputFieldID: '[id="ConfirmPassword"]',
  agreePrivacyPolicyCheckBox: 'input[name="AgreePrivacyPolicy"]',
  agreeNewsLetterCheckBox: 'input[name="AgreeNewsletter"]',
  agreeIdentificationCheckBox: 'input[name="AgreeIdentification"]',
  cancelMainText: 'Cancel',
  invalidFirstNameMainText: 'Invalid first name',
  accountCreatedSuccessMainText: "Account Successfully Created",
  btnSignInID: 'Sign In',
  profileMenuText: 'My Profile',
  emailRequiredErrorMessage: "The Email field is required.",
  passwordRequiredErrorMessage: "The Password field is required.",
  invalidCredentialsMessage: "Invalid username/password pair",
  invalidEmailAddressError: "Invalid email address.",
  viewPasswordButtonID: "[id='showpassword']",
  forgotPasswordButton: "//a[contains(@href,'forgotpassword')]",
  resetPasswordHeading: "Reset Password",
  submitResetPasswordEmailButton: "[data-action='submit']"
};
